/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodscheduler;

/**
 *
 * @author rgiacovazzi
 * Date: 14/03/2025
 * Description: BloodSchedulerGUI is the main class that creates the GUI for the BloodScheduler application. It instantiates the PriorityQueue and Queue classes and allows the user to interact with the application.
 */
public class BloodSchedulerGUI extends javax.swing.JFrame {
    PriorityQueue priorityQueue;
    Queue noShowQueue;
    /**
     * Creates new form BloodSchedulerGUI
     */
    public BloodSchedulerGUI() {
        initComponents();
        priorityQueue = new PriorityQueue();
        noShowQueue = new Queue();
        
        // Initial intake of patents
        Patient p1 = new Patient("Alice", "Urgent", 70, true, "Dr. Smith", "123-456-7890");
        Patient p2 = new Patient("Bob", "Medium", 30, false, "Dr. Johnson", "987-654-3210");
        Patient p3 = new Patient("Charlie", "Low", 5, false, "Dr. Brown", "555-555-5555");
        Patient p4 = new Patient("David", "Urgent", 80, true, "Dr. White", "111-222-3333");
        Patient p5 = new Patient("Eve", "Medium", 40, false, "Dr. Black", "444-555-6666");
        Patient p6 = new Patient("Frank", "Low", 10, false, "Dr. Green", "777-888-9999");
        
        priorityQueue.enqueue(p1);
        priorityQueue.enqueue(p2);
        priorityQueue.enqueue(p3);
        priorityQueue.enqueue(p4);
        priorityQueue.enqueue(p5);
        priorityQueue.enqueue(p6);
        
        priorityQueue.printPQueue();
        noShowTextPane.setText("No Show Queue is empty.");
        try {
            nextPatientTextPane.setText(priorityQueue.getFirst().toString());
            fullPatientListTextPane.setText(priorityQueue.printPQueue());
        } catch (NullPointerException e) {
            nextPatientTextPane.setText("No More Patients");
            fullPatientListTextPane.setText("Empty Full Patients List");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        intakePanel = new javax.swing.JPanel();
        intakeTitleLabel = new javax.swing.JLabel();
        patientIntakeFormPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        patientNameLabel = new javax.swing.JLabel();
        patientNameTextField = new javax.swing.JTextField();
        patientAgeLabel = new javax.swing.JLabel();
        patientAgeTextField = new javax.swing.JTextField();
        patientPriorityComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        hospitalCheckBox = new javax.swing.JCheckBox();
        gpNameLabel = new javax.swing.JLabel();
        gpNameTextField = new javax.swing.JTextField();
        gpPhoneLabel = new javax.swing.JLabel();
        gpPhoneTextField = new javax.swing.JTextField();
        patientIntakeButton = new javax.swing.JButton();
        noShowListPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noShowTextPane = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        testerPanel = new javax.swing.JPanel();
        testerTitleLabel = new javax.swing.JLabel();
        nextPatientPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        nextPatientTextPane = new javax.swing.JTextPane();
        nextPatientButton = new javax.swing.JButton();
        noShowButton = new javax.swing.JButton();
        fullPatientListPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        fullPatientListTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        intakeTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        intakeTitleLabel.setText("Patient Intake Dashboard");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Patient Intake Form");

        patientNameLabel.setText("Patient Name:");

        patientNameTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        patientNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientNameTextFieldActionPerformed(evt);
            }
        });

        patientAgeLabel.setText("Patient Age:");

        patientAgeTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        patientPriorityComboBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        patientPriorityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "Urgent" }));
        patientPriorityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientPriorityComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Patient Priority:");

        hospitalCheckBox.setText("Is the patient from a hospital ward?");
        hospitalCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        hospitalCheckBox.setIconTextGap(20);

        gpNameLabel.setText("GP Name:");

        gpNameTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        gpPhoneLabel.setText("GP Phone Number:");

        gpPhoneTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        patientIntakeButton.setText("Intake Patient");
        patientIntakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIntakeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patientIntakeFormPanelLayout = new javax.swing.GroupLayout(patientIntakeFormPanel);
        patientIntakeFormPanel.setLayout(patientIntakeFormPanelLayout);
        patientIntakeFormPanelLayout.setHorizontalGroup(
            patientIntakeFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientIntakeFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientIntakeFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientIntakeFormPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(349, 349, 349))
                    .addGroup(patientIntakeFormPanelLayout.createSequentialGroup()
                        .addGroup(patientIntakeFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(patientIntakeFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(gpNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(patientIntakeFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(patientIntakeFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(patientPriorityComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 343, Short.MAX_VALUE)
                                        .addComponent(patientNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(patientNameLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel3)))
                            .addComponent(gpNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(patientIntakeFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(patientIntakeFormPanelLayout.createSequentialGroup()
                                .addComponent(gpPhoneLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(patientIntakeFormPanelLayout.createSequentialGroup()
                                .addGroup(patientIntakeFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(patientAgeLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hospitalCheckBox, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientAgeTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                    .addComponent(gpPhoneTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(patientIntakeFormPanelLayout.createSequentialGroup()
                        .addComponent(patientIntakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        patientIntakeFormPanelLayout.setVerticalGroup(
            patientIntakeFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientIntakeFormPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(patientIntakeFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameLabel)
                    .addComponent(patientAgeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientIntakeFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientIntakeFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientPriorityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hospitalCheckBox))
                .addGap(18, 18, 18)
                .addGroup(patientIntakeFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpNameLabel)
                    .addComponent(gpPhoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientIntakeFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(patientIntakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(noShowTextPane);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Latest 5 No Shows");

        javax.swing.GroupLayout noShowListPanelLayout = new javax.swing.GroupLayout(noShowListPanel);
        noShowListPanel.setLayout(noShowListPanelLayout);
        noShowListPanelLayout.setHorizontalGroup(
            noShowListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noShowListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noShowListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        noShowListPanelLayout.setVerticalGroup(
            noShowListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noShowListPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout intakePanelLayout = new javax.swing.GroupLayout(intakePanel);
        intakePanel.setLayout(intakePanelLayout);
        intakePanelLayout.setHorizontalGroup(
            intakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intakePanelLayout.createSequentialGroup()
                .addGroup(intakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(intakeTitleLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(noShowListPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patientIntakeFormPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        intakePanelLayout.setVerticalGroup(
            intakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intakePanelLayout.createSequentialGroup()
                .addComponent(intakeTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientIntakeFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(noShowListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        testerTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        testerTitleLabel.setText("Tester Dashboard");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Next Patient");

        jScrollPane2.setViewportView(nextPatientTextPane);

        nextPatientButton.setText("Next Patient");
        nextPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPatientButtonActionPerformed(evt);
            }
        });

        noShowButton.setText("Patient No Show");
        noShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noShowButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nextPatientPanelLayout = new javax.swing.GroupLayout(nextPatientPanel);
        nextPatientPanel.setLayout(nextPatientPanelLayout);
        nextPatientPanelLayout.setHorizontalGroup(
            nextPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nextPatientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nextPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(nextPatientPanelLayout.createSequentialGroup()
                        .addComponent(nextPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        nextPatientPanelLayout.setVerticalGroup(
            nextPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nextPatientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nextPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nextPatientButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(noShowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Full Patient List");

        jScrollPane3.setViewportView(fullPatientListTextPane);

        javax.swing.GroupLayout fullPatientListPanelLayout = new javax.swing.GroupLayout(fullPatientListPanel);
        fullPatientListPanel.setLayout(fullPatientListPanelLayout);
        fullPatientListPanelLayout.setHorizontalGroup(
            fullPatientListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullPatientListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fullPatientListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        fullPatientListPanelLayout.setVerticalGroup(
            fullPatientListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullPatientListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout testerPanelLayout = new javax.swing.GroupLayout(testerPanel);
        testerPanel.setLayout(testerPanelLayout);
        testerPanelLayout.setHorizontalGroup(
            testerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(testerTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
            .addComponent(nextPatientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fullPatientListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        testerPanelLayout.setVerticalGroup(
            testerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testerPanelLayout.createSequentialGroup()
                .addComponent(testerTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextPatientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fullPatientListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(intakePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(intakePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(testerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientNameTextFieldActionPerformed

    private void patientPriorityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientPriorityComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientPriorityComboBoxActionPerformed

    private void patientIntakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIntakeButtonActionPerformed
        int patientAge = Integer.parseInt(patientAgeTextField.getText());
        Object patientPriority = patientPriorityComboBox.getSelectedItem();
        Patient patient = new Patient(patientNameTextField.getText(), patientPriority.toString(), patientAge, hospitalCheckBox.isSelected(), gpNameTextField.getText(), gpPhoneTextField.getText());
        priorityQueue.enqueue(patient);
        fullPatientListTextPane.setText(priorityQueue.printPQueue());
        nextPatientTextPane.setText(priorityQueue.getFirst().toString());
        
        
//        System.out.println(patient);
    }//GEN-LAST:event_patientIntakeButtonActionPerformed

    private void nextPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPatientButtonActionPerformed
        try {
            if (priorityQueue.size() == 1){
            priorityQueue.dequeue();
            nextPatientTextPane.setText("No More Patients");
            } else {
                priorityQueue.dequeue();
                nextPatientTextPane.setText(priorityQueue.getFirst().toString());
                fullPatientListTextPane.setText(priorityQueue.printPQueue());
            }
        } catch (NullPointerException e) {
            nextPatientTextPane.setText("No More Patients");
        }
        
    }//GEN-LAST:event_nextPatientButtonActionPerformed

    private void noShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noShowButtonActionPerformed
        try {
            noShowQueue.enqueue(priorityQueue.getFirst());
            priorityQueue.dequeue();
            nextPatientTextPane.setText(priorityQueue.getFirst().toString());
            fullPatientListTextPane.setText(priorityQueue.printPQueue());
            noShowTextPane.setText(noShowQueue.printQueue());
        } catch (NullPointerException e) {
            nextPatientTextPane.setText("No More Patients");
            noShowTextPane.setText("No Show Queue is empty.");
            noShowTextPane.setText(noShowQueue.printQueue());
        }
        
    }//GEN-LAST:event_noShowButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fullPatientListPanel;
    private javax.swing.JTextPane fullPatientListTextPane;
    private javax.swing.JLabel gpNameLabel;
    private javax.swing.JTextField gpNameTextField;
    private javax.swing.JLabel gpPhoneLabel;
    private javax.swing.JTextField gpPhoneTextField;
    private javax.swing.JCheckBox hospitalCheckBox;
    private javax.swing.JPanel intakePanel;
    private javax.swing.JLabel intakeTitleLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton nextPatientButton;
    private javax.swing.JPanel nextPatientPanel;
    private javax.swing.JTextPane nextPatientTextPane;
    private javax.swing.JButton noShowButton;
    private javax.swing.JPanel noShowListPanel;
    private javax.swing.JTextPane noShowTextPane;
    private javax.swing.JLabel patientAgeLabel;
    private javax.swing.JTextField patientAgeTextField;
    private javax.swing.JButton patientIntakeButton;
    private javax.swing.JPanel patientIntakeFormPanel;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JTextField patientNameTextField;
    private javax.swing.JComboBox<String> patientPriorityComboBox;
    private javax.swing.JPanel testerPanel;
    private javax.swing.JLabel testerTitleLabel;
    // End of variables declaration//GEN-END:variables
}
